# Generated by Django 4.0.2 on 2022-02-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablerows',
            old_name='Distance',
            new_name='distance',
        ),
    ]
